name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: ahmedbektic/leetcode-records@master
        with:
          github-token: ${{ github.token }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          session-cookie: ${{ secrets.LEETCODE_SESSION }}
